version: '3.8'

services:
  reservation-database:
    image: postgres:latest
    container_name: reservation-database
    environment:
      POSTGRES_DB: reservation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_infoo:/var/lib/postgresql/infoo

  reservation-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservation-service
    ports:
      - "9000:9002"
    environment:
      REGISTRY_SERVER: service-registry
      DB_SERVER: reservation-database
      MANAGEMENT_METRICS_TAGS_APPLICATION: reservation-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_SERVICE_NAME: reservation-service
      OTEL_RESOURCE_ATTRIBUTES: compose_service=reservation-service
      OTEL_METRICS_EXPORTER: none
    depends_on:
      - reservation-database
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test123
    ports:
      - "5050:80"

volumes:
  postgres_infoo:
